# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Aurora Sweep'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[ "nice_nano_v2" ]'
      shield: '[ "splitkb_aurora_sweep_left nice_view_adapter nice_view", "splitkb_aurora_sweep_right nice_view_adapter nice_view" ]' 
      nav: 'vi'
      kconfig: '["CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y"]'
